version: 0.0
os: linux
files:
  - source: /build/libs/app.war
    destination: /home/maintenance
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: yllapito
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: yllapito

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: yllapito
  
